- id: "12345"
  alias: "MVHR Input Select Publish"
  trigger:
    platform: state
    entity_id: sensor.mvhr_speed_select_state
  action:
    service: mqtt.publish
    data_template:
      topic: >
        {% if states('sensor.mvhr_speed_select_state') == 'Speed 0 (Away)' %}
          comfoair/commands/ventilation_level_0
        {% elif states('sensor.mvhr_speed_select_state') == 'Speed 1' %}
          comfoair/commands/ventilation_level_1
        {% elif states('sensor.mvhr_speed_select_state') == 'Speed 2 (Default)' %}
          comfoair/commands/ventilation_level_2
        {% elif states('sensor.mvhr_speed_select_state') == 'Speed 3 (Boost)' %}
          comfoair/commands/ventilation_level_3
        {% else %}
          comfoair/commands/ventilation_level_2
        {% endif %}
      payload: "on"

- id: "12346"
  alias: "MVHR Input Select Update"
  trigger:
    platform: state
    entity_id: sensor.mvhr_supply_fan_user_speed
  action:
    service: input_select.select_option
    data_template:
      entity_id: input_select.mvhr_ventilation_speed
      option: >
        {% if states('sensor.mvhr_supply_fan_user_speed') == "0" %}
          Speed 0 (Away)
        {% elif states('sensor.mvhr_supply_fan_user_speed') == "1" %}
          Speed 1
        {% elif states('sensor.mvhr_supply_fan_user_speed') == "2" %}
          Speed 2 (Default)
        {% elif states('sensor.mvhr_supply_fan_user_speed') == "3" %}
          Speed 3 (Boost)
        {% else %}
          Speed 2 (Default)
        {% endif %}

